version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://taskapp:taskapp123@db:5432/taskmanager
      - NEXTAUTH_SECRET=your-super-secret-auth-key
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
  
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: taskapp
      POSTGRES_PASSWORD: taskapp123
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
