import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        {session ? (
          children
        ) : (
          <div className="flex min-h-screen flex-col items-center justify-center">
            <div className="text-center">
              <h1 className="text-3xl font-bold mb-4">Task Management App</h1>
              <p className="mb-4">Please sign in to continue</p>
              <Link
                href="/api/auth/signin"
                className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground ring-offset-background transition-colors hover:bg-primary/90"
              >
                Sign In
              </Link>
            </div>
          </div>
        )}
        <Toaster />
      </body>
    </html>
  );
}
