name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: taskapp
          POSTGRES_PASSWORD: taskapp123
          POSTGRES_DB: taskmanager
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run database migrations
        run: npx prisma db push
        env:
          DATABASE_URL: postgresql://taskapp:taskapp123@localhost:5432/taskmanager

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: postgresql://taskapp:taskapp123@localhost:5432/taskmanager
          NEXTAUTH_SECRET: your-super-secret-auth-key
          NEXTAUTH_URL: http://localhost:3000

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://taskapp:taskapp123@localhost:5432/taskmanager
          NEXTAUTH_SECRET: your-super-secret-auth-key
          NEXTAUTH_URL: http://localhost:3000